// Code generated by iniziamo. DO NOT EDIT.
package example

import (
	"context"
)

type AuthServiceClientConfig struct {
	Scheme string //http|https
	Host   string
	Port   int
}

type AuthServiceClient interface {
	Login(
		context.Context, *authServiceClientLoginRequest,
	) (
		*authServiceClientLoginResponse, error,
	)

	Logout(
		context.Context, *authServiceClientLogoutRequest,
	) (
		*authServiceClientLogoutResponse, error,
	)
}

type authServiceClientImpl struct {
	//TODO
}

func NewAuthServiceClient() AuthServiceClient {
	return &authServiceClientImpl{
		//TODO
	}
}

type authServiceClientLoginRequest struct {
	continueURL string

	continueURLSet bool
}

func AuthServiceClientLoginRequest() *authServiceClientLoginRequest {
	return &authServiceClientLoginRequest{
		//TODO
	}
}

func (r *authServiceClientLoginRequest) ContinueURL(value string) *authServiceClientLoginRequest {
	r.continueURL = value
	r.continueURLSet = true
	return r
}

type authServiceClientLoginResponse struct {
	//TODO
}

func AuthServiceClientLoginResponse() *authServiceClientLoginResponse {
	return &authServiceClientLoginResponse{
		//TODO
	}
}

func (c *authServiceClientImpl) Login(
	context.Context, *authServiceClientLoginRequest,
) (
	*authServiceClientLoginResponse, error,
) {
	//TODO
	return nil, nil
}

type authServiceClientLogoutRequest struct {
}

func AuthServiceClientLogoutRequest() *authServiceClientLogoutRequest {
	return &authServiceClientLogoutRequest{
		//TODO
	}
}

type authServiceClientLogoutResponse struct {
	//TODO
}

func AuthServiceClientLogoutResponse() *authServiceClientLogoutResponse {
	return &authServiceClientLogoutResponse{
		//TODO
	}
}

func (c *authServiceClientImpl) Logout(
	context.Context, *authServiceClientLogoutRequest,
) (
	*authServiceClientLogoutResponse, error,
) {
	//TODO
	return nil, nil
}
